#!/bin/sh

# -----------------------------------------------------------------------------
# script to build AWS Lambda packages in a virtualenv environment - assumes $1
# contains the name of a python file and we're running from the directory 
# containing the file.
#
# We need to be running in virtualenv - i.e. we've done a source bin/activate
# at some point.
#
# -----------------------------------------------------------------------------

file=$1

if [ ! -f $file ]
then
    echo "Missing file: ${file}" >&2
    exit 1
fi

if [ -z "${VIRTUAL_ENV}" ] || [ ! -d lib/python2.7/site-packages ]
then
    echo "Can't find the package libraries"
    exit 2
fi

zipfile=$(echo $file | sed "s/py$/zip/g")

# If zip file already exists, delete it
if [ -f $zipfile ]
then
    rm $zipfile
fi

echo "Adding ${file} to package"
zip -9q ${zipfile} ${file} 
if [ $? -ne 0 ]
then
    echo "Initial package build failed" >&2
    exit 1
fi

for pkg in $(grep "import" $1 | awk '{print $2}'| egrep -v 'boto3|pprint|json|^re$|datetime|random|__future__')
do
    # Is it a file in the current directory ?
    if [ -f ${pkg} ]
    then
        echo "Adding ${pkg} to package"
        zip -q9 ${zipfile} ${pkg}
    elif [ -f ${pkg}.py ]
    then
        echo "Adding ${pkg}.py to package"
        zip -q9 ${zipfile} ${pkg}.py
    else
        cd lib/python2.7/site-packages
        echo "Added ${pkg} library to package"
        zip -rq9 ../../../${zipfile} ${pkg}
        if [ $? -ne 0 ]
        then
            echo "Adding library ${pkg} failed" >&2
            exit 2
        fi
    fi
    
    cd ../../..
done

echo "Package now in place at ${zipfile}"
